services:
  api:
    build:
      context: api
    command: gunicorn --conf gunicorn.conf.py maps.app:app
    environment:
      GUNICORN_ACCESSLOG: "-"
      GUNICORN_BIND: 0.0.0.0:9090
      GUNICORN_CAPTURE_OUTPUT: "true"
      GUNICORN_ERRORLOG: "-"
      GUNICORN_LOGLEVEL: debug
      GUNICORN_RELOAD: "true"
      GUNICORN_WORKERS: 4
      GUNICORN_WORKER_CLASS: aiohttp.worker.GunicornUVLoopWebWorker
      GUNICORN_ENABLE_STDIO_INHERITANCE: "true"
    ports:
    - 9090:9090
    volumes:
    - ./api:/app
    - ./data:/data
  gui:
    build:
      context: gui
    ports:
    - 8080:80
    volumes:
    - ./gui/dist:/var/www/html
  postgres:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:18
    ports:
    - 5432:5432
