[build-system]
build-backend = "setuptools.build_meta"
requires = ["Cython", "setuptools", "wheel"]

[project]
name = "maps"
version = "0.1.0"
description = "On Exactitude in Science"
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "alembic",
  "asyncpg",
  "click",
  "fastapi",
  "gunicorn",
  "lxml",
  "sqlalchemy",
  "uqbar",
  "uvicorn-worker",
  "uvloop",
]

[project.optional-dependencies]
test = [
  "mypy",
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "ruff",
  "types-lxml",
  "types-tqdm",
]

[project.urls]
homepage = "https://github.com/josephine-wolf-oberholtzer/on-exactitude-in-science"
documentation = "https://josephine-wolf-oberholtzer.github.io/on-exactitude-in-science"
repository = "https://github.com/josephine-wolf-oberholtzer/on-exactitude-in-science"

[tool.mypy]
plugins = ["mypy_plugin_lxml.main"]

[tool.pytest]
addopts = ["-rf", "-vv"]
log_format = "%(levelname)-8s %(name)s:%(filename)s:%(lineno)-4d %(message)s"

[tool.ruff]
line-length = 88
target-version = "py314"
